name: clone workflow
on:
  workflow_dispatch:
jobs:
  clone:
    name: Clone
    runs-on: ubuntu-latest
    steps:
      - name: cloning_website_repo_host
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          password: ${{ secrets.PASSWORD }}
          port: ${{ secrets.PORT }}
          script: git clone git@github.com:nachado12/cmsc389T-website.git
